# Change these first
owner: CaminoScan # Your GitHub organization or username, where this repository lives
repo: camino-status # The name of this repository

sites:
  - name: CaminoScan - Camino Mainnet
    url: https://caminoscan.com
  - name: CaminoScan - Columbus Testnet 
    url: https://columbus.caminoscan.com
  - name: Camino Network Homepage
    url: https://camino.network
  - name: Camino Mainnet RPC Endpoint - Ping
    check: "tcp-ping"
    url: api.camino.network
    port: 443
  - name: Columbus Testnet RPC Endpoint - Ping
    check: "tcp-ping"
    url: columbus.camino.network
    port: 443
  - name: Camino Mainnet RPC Endpoint - POST
    method: POST
    url: https://api.camino.network/ext/info
    headers:
      - "Content-Type: application/json"
    body: '{"jsonrpc":"2.0","id":1,"method":"info.getNetworkName"}'
  - name: Columbus Testnet RPC Endpoint - POST
    method: POST
    url: https://columbus.camino.network/ext/info
    headers:
      - "Content-Type: application/json"
    body: '{"jsonrpc":"2.0","id":1,"method":"info.getNetworkName"}'

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /camino-status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Camino Ecosystem Status
  introTitle: "Status page for Camino Network ecosystem."
  introMessage: This status page uses **real-time** data from our [GitHub repository](https://github.com/CaminoScan/camino-status).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
